import '../styles/globals.css'
import styles from '../styles/Home.module.css'
import Head from 'next/head'


function MyApp({ Component, pageProps }) {
  return (
    <div className={styles.container}>
    <Head>
      <title>Notes Web App</title>
      <meta name="description" content="Generated by Yinon" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={styles.main}>
      <h1 className={styles.title}>
        Welcome to Notes App
      </h1>


      <Component {...pageProps} />
    </main>
  </div>
  )
    
   
}

export default MyApp
